name: Fetch This Figure
description: Request a specific figure to be included in PFOCR
title: "[Fetch] Please include this pathway figure"
labels: ["fetch"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using the Figure Fetcher! Please provide the following information:
  - type: input
    id: pmcid
    attributes:
      label: PMCID
      description: The PubMed Central ID of the article containing the figure
      placeholder: e.g., PMC9949038
    validations:
      required: true
  - type: input
    id: figure_number
    attributes:
      label: Figure Number
      description: The number of the figure you want to fetch.
      placeholder: e.g., 3
    validations:
      required: true
