name: Reset figure fetch

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 1 1,4,7,10 *" #Runs at 0:00 on the first of each quarter. 
  
jobs:
  reset-figure-fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Reset last_run in query_config.yml
      run: |
        DATE_15_MONTHS_AGO=$(date -d "15 months ago" +%Y/%m/%d)
        sed -i "s|last_run:.*|last_run: $DATE_15_MONTHS_AGO|" query_config.yml

  
    - name: Commit updated config file
      uses: stefanzweifel/git-auto-commit-action@v4  
      with:
        commit_message: new figures from pmc; updated config and log
