name: Fetch this figure

on:
  issues:
    types: [opened, labeled]

jobs:
  fetch-figure:
    if: github.event.label.name == 'fetch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.1'
    
    - name: Install dependencies
      run: |
        R -e 'install.packages(c("rentrez", "xml2", "httr", "yaml", "stringr", "tools"))'
    
    - name: Extract PMCID and Figure Number
      id: extract
      run: |
        body="${{ github.event.issue.body }}"
        pmcid=$(echo "$body" | awk '/^### PMCID/{getline; print}')
        figure_number=$(echo "$body" | awk '/^### Figure Number/{getline; print}')
        echo "pmcid=$pmcid" >> $GITHUB_OUTPUT
        echo "figure_number=$figure_number" >> $GITHUB_OUTPUT
    
    - name: Fetch Figure
      run: |
        Rscript fetch_THIS_figure_v2.R ${{ steps.extract.outputs.pmcid }} ${{ steps.extract.outputs.figure_number }}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Add figure ${{ steps.extract.outputs.pmcid }}_${{ steps.extract.outputs.figure_number }}
        title: Add figure ${{ steps.extract.outputs.pmcid }}_${{ steps.extract.outputs.figure_number }}
        body: |
          This PR adds a new figure:
          - PMCID: ${{ steps.extract.outputs.pmcid }}
          - Figure Number: ${{ steps.extract.outputs.figure_number }}
        branch: add-figure-${{ steps.extract.outputs.pmcid }}-${{ steps.extract.outputs.figure_number }}
        delete-branch: true
