name: Fetch this figure

on:
  issues:
    types: [labeled]

jobs:
  fetch-figure:
    if: github.event.label.name == 'fetch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.1'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        Rscript -e 'install.packages(c("rentrez", "xml2", "httr", "yaml", "stringr"))'
    
    - name: Extract PMCID and Figure Number
      id: extract
      run: |
        echo "Issue body:"
        echo "${{ github.event.issue.body }}"
        echo "---"
        pmcid=$(grep -A1 "### PMCID" <<< "${{ github.event.issue.body }}" | tail -n1 | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
        figure_number=$(grep -A1 "### Figure Number" <<< "${{ github.event.issue.body }}" | tail -n1 | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
        echo "Extracted PMCID: '$pmcid'"
        echo "Extracted Figure Number: '$figure_number'"
        echo "pmcid=$pmcid" >> $GITHUB_OUTPUT
        echo "figure_number=$figure_number" >> $GITHUB_OUTPUT
    
    - name: Fetch Figure
      run: |
        Rscript scripts/fetch_THIS_figure_v2.R "${{ steps.extract.outputs.pmcid }}" "${{ steps.extract.outputs.figure_number }}"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Add figure ${{ steps.extract.outputs.pmcid }}_${{ steps.extract.outputs.figure_number }}
        title: Add figure ${{ steps.extract.outputs.pmcid }}_${{ steps.extract.outputs.figure_number }}
        body: |
          This PR adds a new figure:
          - PMCID: ${{ steps.extract.outputs.pmcid }}
          - Figure Number: ${{ steps.extract.outputs.figure_number }}
        branch: add-figure-${{ steps.extract.outputs.pmcid }}-${{ steps.extract.outputs.figure_number }}
        delete-branch: true
