name: Keep Figids for OCR

on:
  pull_request:
    types:
      - closed

jobs:
  update-figids:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'fetch')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract figid from PR title
      id: extract_figid
      run: |
        figid=$(echo "${{ github.event.pull_request.title }}" | sed 's/Add figure //')
        echo "figid=$figid" >> $GITHUB_OUTPUT

    - name: Update keep_figids_for_ocr.txt
      run: |
        if [ ! -f keep_figids_for_ocr.txt ]; then
          echo "${{ steps.extract_figid.outputs.figid }}" > keep_figids_for_ocr.txt
        else
          echo "${{ steps.extract_figid.outputs.figid }}" >> keep_figids_for_ocr.txt
        fi

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keep_figids_for_ocr.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update keep_figids_for_ocr.txt with ${{ steps.extract_figid.outputs.figid }}" && git push)
